### ISSUE TITLE
No relation stats, and no ckanpackager-cli.json

### ISSUE THREAD

**Issue by LukeTully** [NaturalHistoryMuseum/ckanpackager#35]
I noticed that the ckanpackager-cli relies on a ckanpackager-cli.json to function, but there isn't an example in the repo to go on. Is this no longer in use? If I'm running ckanpackager with apache and it's respective WSGI configuration, do I need the ckanpackager-cli? I'm not sure if it's related to any of the issues I'm currently running into in the deployment of ckanpackager.

Secondly, I'm getting the following error that I haven't yet been able to track down.
https://pastebin.com/8WxNvn6V

Seems to suggest that a the ckanpackager_stats table wasn't created, but haven't been able to track down where I might have gone wrong in the setup process.

**Comment by jrdh** [comment]
There's a description in the cli source code of what `ckanpackager-cli.json` should contain: https://github.com/NaturalHistoryMuseum/ckanpackager/blob/master/ckanpackager/cli.py#L24. We use this file currently in production and it just contains the secret, so `{"secret": "<whatever our secret is>"}`. The cli isn't required to use the ckanpackager, all it really provides is just cli access to stats and status data.

Regarding the second point, that's actually an issue from the [ckanext-ckanpackager](https://github.com/NaturalHistoryMuseum/ckanext-ckanpackager) extension which accompanies this service. All you need to do is run the [initdb command](https://github.com/NaturalHistoryMuseum/ckanext-ckanpackager/blob/master/ckanext/ckanpackager/commands/initdb.py) and that should generate the database for you. I'll update the readme on that repo with details in a moment as it isn't mentioned anywhere - sorry about that!

**Comment by jrdh** [comment]
Updated readme: https://github.com/NaturalHistoryMuseum/ckanext-ckanpackager#database-initialisation

**Comment by LukeTully** [comment]
@jrdh Thanks, both of those tips helped.
